# The MIT License (MIT)
#
# SPDX-FileCopyrightText: Copyright (c) 2015-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: copyrights
'on':
  push:
  pull_request:
jobs:
  copyrights:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: yegor256/copyrights-action@0.0.8
